image:
  repository: 724133491284.dkr.ecr.us-east-1.amazonaws.com/clipgen
  tag: v22
  pullSecrets:
    - name: aws-ecr-secret  # ECR credentials

aws:
  region: us-east-1
  queueUrl: "https://sqs.us-east-1.amazonaws.com/724133491284/clipgen-processing"
  jobTableName: "clipgen-jobs"
  mediaBucketName: "clipgen-media"

scaling:
  minReplicas: 1 # Start with 1 for testing
  maxReplicas: 4
  queueLength: "2"

# Set to {} to disable node selection for testing on any available node.
# Or specify the correct hostname for your GPU node.
nodeSelector:
  kubernetes.io/hostname: g094

resources:
  requests:
    cpu: 20000m
    memory: 200Gi
    nvidia.com/gpu: 2
  limits:
    cpu: 24000m
    memory: 200Gi
    nvidia.com/gpu: 2
  shmSize: "60Gi"  # 30% of 200Gi RAM for Ray shared memory

worker:
  maxConcurrentJobs: 1 # Multi-GPU uses both GPUs for one job
  cudaVisibleDevices: "0,1"
